import Script from "next/script";
import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "@/components/common/Sidebar";
import FooterScripts from "@/components/common/FooterScripts";
import Footer from "@/components/common/Footer";
import Navbar from "@/components/common/Navbar";
import HeaderScript from "../components/common/HeaderScript";
import MainLayout from "../components/layout/MainLayout";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mediasoft Support",
  deScription: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      class="light-style layout-navbar-fixed layout-menu-fixed layout-footer-fixed"
      dir="ltr"
      data-theme="theme-default"
      data-assets-path="assets/"
      data-template="vertical-menu-template"
    >
      <HeaderScript />
      <body className={inter.className}>
        <div class="layout-wrapper layout-content-navbar ">
          <MainLayout>
            {children}
          </MainLayout>
        </div>
        <FooterScripts />
      </body>
    </html>
  );
}
